version: '3'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    command: "sleep infinity"
    volumes:
      - ./:/code
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - ./static:/home/www/static:ro
      - ./media:/home/www/media:ro
