# Generated by Django 3.1.1 on 2020-09-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200905_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='human_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя для отображения в шаблонах'),
        ),
        migrations.AddField(
            model_name='tag',
            name='style',
            field=models.CharField(max_length=255, null=True, verbose_name='Префикс стиля для шаблона'),
        ),
    ]
