# Generated by Django 3.1.1 on 2020-09-17 18:50
import os
import shutil

from django.db import migrations
from django.core.management import call_command
from django.conf import settings

import recipes


def load_fixtures(apps, schema_editor):
    call_command('loaddata', 'initial_data.json', app_label='recipes')


def copy_images_to_media(apps, schema_editor):
    img_src = os.path.join(os.path.dirname(recipes.__file__), 'fixtures', 'images')
    shutil.copytree(img_src, settings.MEDIA_ROOT / 'recipes')


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200909_1645'),
    ]

    operations = [
        migrations.RunPython(load_fixtures),
        migrations.RunPython(copy_images_to_media),
    ]
